<a href="https://colab.research.google.com/github/beotavalo/ML-DL-Applications/blob/main/Tensor_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to tensor, tensor libraries, and tensor calculation
In this lab, we are going to use the two most popular frameworks used in Deep Learning [PyTorch](https://pytorch.org/) and [TensorFlow](https://www.tensorflow.org/).

In [16]:
import torch
import tensorflow as tf

print(f"PyTorch version: {torch.__version__}")
print(f"TensorFlow version: {tf.__version__}")


PyTorch version: 2.3.0+cu121
TensorFlow version: 2.15.0


In [17]:
# Create a tensor with the both PyTorch
w = torch.ones(2, 3, 2)
x = torch.rand(2,3, 2) #Random tensor nxm

# Create a tensor with the TensorFlow
y = tf.ones((2, 3, 3))
z = tf.random.uniform((2, 3, 3)) #Random tensor nxm

# Add the tensors
torch_sum = torch.add(w, x)
tf_sum = tf.add(y, z)

# Print the results
print("PyTorch sum:")
print(torch_sum)
print("\nTensorFlow sum:")
print(tf_sum)



PyTorch sum:
tensor([[[1.5067, 1.7450],
         [1.7303, 1.9192],
         [1.0893, 1.0359]],

        [[1.2707, 1.2528],
         [1.4814, 1.1896],
         [1.8674, 1.5155]]])

TensorFlow sum:
tf.Tensor(
[[[1.2626388 1.0979536 1.4551301]
  [1.305712  1.2043009 1.4468613]
  [1.4253085 1.4531769 1.7109005]]

 [[1.5692545 1.0063932 1.655444 ]
  [1.5986255 1.3533288 1.8927387]
  [1.3101932 1.438307  1.4142678]]], shape=(2, 3, 3), dtype=float32)


The shape of a Tensor defines its number of dimensions and the size of each dimension. The rank of a Tensor provides the number of dimensions (n-dimensions) -- you can also think of this as the Tensor's order or degree.

Reference in this [link](https://github.com/aamini/introtodeeplearning/blob/master/lab1/solutions/Part1_TensorFlow_Solution.ipynb)

In [18]:
# Shape and Rank of tensor in PyTorch

print("Shape of `w`:", w.shape)
print("Rank of `w`:", w.ndim)
print("Shape of `x`:", x.shape)
print("Rank of `x`:", x.ndim)

#Shape and Rank of tensor in tensorflow
print("`y` is a {}-d Tensor".format(tf.shape(y).numpy()))
print("`z` is a {}-d Tensor".format(tf.shape(z).numpy()))
print("`y` is a {}-d Tensor".format(tf.rank(y).numpy()))
print("`z` is a {}-d Tensor".format(tf.rank(z).numpy()))

Shape of `w`: torch.Size([2, 3, 2])
Rank of `w`: 3
Shape of `x`: torch.Size([2, 3, 2])
Rank of `x`: 3
`y` is a [2 3 3]-d Tensor
`z` is a [2 3 3]-d Tensor
`y` is a 3-d Tensor
`z` is a 3-d Tensor


In [19]:
sport = tf.constant("Tennis", tf.string)
number = tf.constant(1.41421356237, tf.float64)

print("`sport` is a {}-d Tensor".format(tf.rank(sport).numpy()))
print("`number` is a {}-d Tensor".format(tf.rank(number).numpy()))

`sport` is a 0-d Tensor
`number` is a 0-d Tensor


In [20]:
music_genre = tf.constant(["Salsa", "Rock", 'Blues'], tf.string)
numbers = tf.constant([2.1356, 4.674, 0.782, -0.235], tf.float64)

print("`music genre` is a {}-d Tensor with shape: {}".format(tf.rank(music_genre).numpy(), tf.shape(music_genre)))
print("`numbers` is a {}-d Tensor with shape: {}".format(tf.rank(numbers).numpy(), tf.shape(numbers)))

`music genre` is a 1-d Tensor with shape: [3]
`numbers` is a 1-d Tensor with shape: [4]


To work with strings using PyTorch should Install a version of PyTorch that supports the string data type
torch==1.13

```!pip install torch==1.13```

In [21]:
numbers = torch.tensor([2.1356, 4.674, 0.782, -0.235], dtype=torch.float64)

print("`numbers` is a {}-d Tensor with shape: {}".format(numbers.dim(), numbers.shape))


`numbers` is a 1-d Tensor with shape: torch.Size([4])


In [22]:
### Defining higher-order Tensors ###

'''TODO: Define a 2-d Tensor'''
matrix = tf.constant([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]]) # TODO
# matrix = # TODO

assert isinstance(matrix, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(matrix).numpy() == 2

'''TODO: Define a 4-d Tensor.'''
# Use tf.zeros to initialize a 4-d Tensor of zeros with size 10 x 256 x 256 x 3.
#   You can think of this as 10 images where each image is RGB 256 x 256.
images = tf.zeros([10, 256, 256, 3]) # TODO
# images = # TODO

assert isinstance(images, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(images).numpy() == 4, "matrix must be of rank 4"
assert tf.shape(images).numpy().tolist() == [10, 256, 256, 3], "matrix is incorrect shape"



In [23]:
row_vector = matrix[0]
column_vector = matrix[:,3]
scalar = matrix[0, 3]

print("`row_vector`: {}".format(row_vector.numpy()))
print("`column_vector`: {}".format(column_vector.numpy()))
print("`scalar`: {}".format(scalar.numpy()))

`row_vector`: [1. 2. 3. 4.]
`column_vector`: [4. 8.]
`scalar`: 4.0


In [24]:
images = torch.zeros((10, 256, 256, 3))


In [25]:
matrix_torch = torch.tensor([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]])
row_vector_torch = matrix_torch[0]
column_vector_torch = matrix_torch[:,3]
scalar_torch = matrix_torch[0, 3]

print("`row_vector`: {}".format(row_vector_torch.numpy()))
print("`column_vector`: {}".format(column_vector_torch.numpy()))
print("`scalar`: {}".format(scalar_torch.numpy()))


`row_vector`: [1. 2. 3. 4.]
`column_vector`: [4. 8.]
`scalar`: 4.0


**Computation on Tensors**

In [26]:
s1 = tf.constant(1.0)
s2 = tf.constant(2.0)

#Add
s3 = s1 + s2
s3_op = tf.add(s1, s2)
#Multiply
s4 = s1 * s2
#Subtract
s5 = s1 - s2
#Division
s6 = s1 / s2

print("`s3`: {}".format(s3.numpy()))
print("`s4`: {}".format(s4.numpy()))
print("`s5`: {}".format(s5.numpy()))
print("`s6`: {}".format(s6.numpy()))
print("`s3_op`: {}".format(s3_op.numpy()))


`s3`: 3.0
`s4`: 2.0
`s5`: -1.0
`s6`: 0.5
`s3_op`: 3.0


In [27]:
s1 = tf.constant([1.0, 2.5])
s2 = tf.constant([2.0, 6.3])

#Add
s3 = s1 + s2
s3_op = tf.add(s1, s2)
#Multiply
s4 = s1 * s2
#Subtract
s5 = s1 - s2
#Division
s6 = s1 / s2

print("`s3`: {}".format(s3.numpy()))
print("`s4`: {}".format(s4.numpy()))
print("`s5`: {}".format(s5.numpy()))
print("`s6`: {}".format(s6.numpy()))
print("`s3_op`: {}".format(s3_op.numpy()))

`s3`: [3.  8.8]
`s4`: [ 2.   15.75]
`s5`: [-1.        -3.8000002]
`s6`: [0.5        0.39682537]
`s3_op`: [3.  8.8]


In [28]:
s1 = torch.tensor([1.0, 2.5])
s2 = torch.tensor([2.0, 6.3])
#Add
s3 = s1 + s2
s3_op = torch.add(s1, s2)
#Multiply
s4 = s1 * s2
#Subtract
s5 = s1 - s2
#Division
s6 = s1 / s2

print("`s3`: {}".format(s3.numpy()))
print("`s4`: {}".format(s4.numpy()))
print("`s5`: {}".format(s5.numpy()))
print("`s6`: {}".format(s6.numpy()))
print("`s3_op`: {}".format(s3_op.numpy()))

`s3`: [3.  8.8]
`s4`: [ 2.   15.75]
`s5`: [-1.        -3.8000002]
`s6`: [0.5        0.39682537]
`s3_op`: [3.  8.8]


**Neural networks**

"\n",
        "![alt text](https://raw.githubusercontent.com/aamini/introtodeeplearning/master/lab1/img/computation-graph-2.png)\n",
        "\n"

In [29]:
# Define the input placeholder
X = tf.keras.Input(shape = (2,), dtype = tf.float32)

# Define the weights and bias
W = tf.Variable(tf.random.truncated_normal([2, 1], stddev=0.1), name='weight')
b = tf.Variable(tf.zeros([1]), name='bias')

# Define placeholder for true labels
y_true = tf.keras.Input(shape=(1,), dtype=tf.float32) # Placeholder for true labels

# Define the model
def my_model(X):
    y_pred = tf.matmul(X, W) + b
    activation = tf.sigmoid(y_pred)
    return activation

# Define the loss function
def my_loss(y_true, y_pred):
    return tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y_true, logits=y_pred))

# Define the optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

# Train the model
def train_step(X_train, y_train):
    with tf.GradientTape() as tape: # Use GradientTape to track computations
        y_pred = my_model(X_train)
        loss_value = my_loss(y_train, y_pred)
    grads = tape.gradient(loss_value, [W, b]) # Calculate gradients
    optimizer.apply_gradients(zip(grads, [W, b])) # Apply gradients
    return loss_value



# Initialize the variables
# Create some example training data
X_train = tf.constant([[1.0, 2.0], [3.0, 4.0]]) # Example training features
y_train = tf.constant([[0.0], [1.0]]) # Example training labels
# Train the model - No session required
for i in range(1000):
    # Assuming X_train and y_train are defined elsewhere
    loss_value = train_step(X_train, y_train)
    if i % 100 == 0:
        print("Loss at step {}: {}".format(i, loss_value))

# Make predictions - No session required
# Assuming X_test is defined elsewhere
# Create some example test data
X_test = tf.constant([[2.0, 3.0]]) # Example test features
predictions = my_model(X_test)
print("Predictions: {}".format(predictions))

Loss at step 0: 0.7298864126205444
Loss at step 100: 0.6528460383415222
Loss at step 200: 0.6007171869277954
Loss at step 300: 0.5688238143920898
Loss at step 400: 0.5496795177459717
Loss at step 500: 0.5377026200294495
Loss at step 600: 0.5298115015029907
Loss at step 700: 0.5243597030639648
Loss at step 800: 0.5204384326934814
Loss at step 900: 0.5175217390060425
Predictions: [[0.5129538]]


In [30]:
# Repeat the previous example using pytorch
import torch
import torch.nn as nn
import torch.optim as optim

# Define the input placeholder
X = torch.randn(2, 2)

# Define the weights and bias
W = torch.randn(2, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Define placeholder for true labels
y_true = torch.randn(2,1)

# Define the model
def my_model(X):
    y_pred = torch.matmul(X, W) + b
    activation = torch.sigmoid(y_pred)
    return activation

# Define the loss function
def my_loss(y_true, y_pred):
    return torch.nn.functional.binary_cross_entropy(y_pred, y_true)

# Define the optimizer
optimizer = optim.Adam([W, b], lr=0.01)

# Train the model
for i in range(1000):
    # Forward pass
    y_pred = my_model(X)
    loss = my_loss(y_true, y_pred)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print the loss every 100 iterations
    if i % 100 == 0:
        print("Loss at step {}: {}".format(i, loss.item()))

# Make predictions
X_test = torch.randn(1, 2)
predictions = my_model(X_test)
print("Predictions: {}".format(predictions))


Loss at step 0: 1.0158309936523438
Loss at step 100: 0.6820676326751709
Loss at step 200: 0.6658444404602051
Loss at step 300: 0.6531088352203369
Loss at step 400: 0.645041823387146
Loss at step 500: 0.6406632661819458
Loss at step 600: 0.6385765075683594
Loss at step 700: 0.6376936435699463
Loss at step 800: 0.6373607516288757
Loss at step 900: 0.6372488141059875
Predictions: tensor([[0.8582]], grad_fn=<SigmoidBackward0>)


In [35]:
# Create a sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, activation='sigmoid', input_shape=(2,)),
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy')

# Train the model
model.fit(X_train, y_train, epochs=1000)

# Make predictions
#predictions = model.predict(X_test)

# Make predictions
# Convert PyTorch tensor to a NumPy array and then to a TensorFlow tensor
X_test = tf.constant([[2.0, 3.0]]) # Example test features
#X_test_tf = tf.convert_to_tensor(X_test_np, dtype=tf.float32)
predictions = model.predict(X_test)

# Print the predictions
print("Predictions: {}".format(predictions))


Epoch 1/1000
1/1 [==============================] - 0s 451ms/step - loss: 2.6324
Epoch 2/1000
1/1 [==============================] - 0s 10ms/step - loss: 2.6286
Epoch 3/1000
1/1 [==============================] - 0s 14ms/step - loss: 2.6248
Epoch 4/1000
1/1 [==============================] - 0s 8ms/step - loss: 2.6210
Epoch 5/1000
1/1 [==============================] - 0s 7ms/step - loss: 2.6172
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 2.6134
Epoch 7/1000
1/1 [==============================] - 0s 7ms/step - loss: 2.6096
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 2.6058
Epoch 9/1000
1/1 [==============================] - 0s 9ms/step - loss: 2.6020
Epoch 10/1000
1/1 [==============================] - 0s 10ms/step - loss: 2.5982
Epoch 11/1000
1/1 [==============================] - 0s 9ms/step - loss: 2.5944
Epoch 12/1000
1/1 [==============================] - 0s 9ms/step - loss: 2.5906
Epoch 13/1000
1/1 [========================

In [37]:
import torch


X_train = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) # Example training features
y_train = torch.tensor([[0.0], [1.0]]) # Example training labels
X_test = torch.tensor([[2.0, 3.0]])
# Create a sequential model
model = torch.nn.Sequential(
    torch.nn.Linear(2, 1),
    torch.nn.Sigmoid(),
)

# Define the optimizer and loss function
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = torch.nn.BCELoss()

# Train the model
for epoch in range(1000):
    # Forward pass
    y_pred = model(X_train)
    loss = loss_fn(y_pred, y_train)

    # Backward pass and update weights
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Make predictions

predictions = model(X_test)

# Print the predictions
print("Predictions:", predictions)

Predictions: tensor([[0.6017]], grad_fn=<SigmoidBackward0>)
